import { Inter } from 'next/font/google'
import './globals.css'
import MainHeader from './components/MainHeader'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>bellx sofwares</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </head>

      {/* preload all images in . folder */}
      <link rel="preload" href="./about.svg" as="image" />
      <link rel="preload" href="./angular-icon.svg" as="image" />
      <link rel="preload" href="./bellx-iclogoon.svg" as="image" />
      <link rel="preload" href="./daniel.svg" as="image" />
      <link rel="preload" href="./developing.svg" as="image" />
      <link rel="preload" href="./ecommerce.svg" as="image" />
      <link rel="preload" href="./image1.svg" as="image" />
      <link rel="preload" href="./image2.svg" as="image" />
      <link rel="preload" href="./image3.svg" as="image" />
      <link rel="preload" href="./image4.svg" as="image" />
      <link rel="preload" href="./kalkidan.svg" as="image" />
      
      <link rel="preload" href="/images/hero.jpg" as="image" />
      <body className={inter.className}>
        <MainHeader />
        {children}
        <Footer />
        </body>
    </html>
  )
}
